#!/bin/sh

STAGED=$(git diff --cached --name-only --diff-filter=ACM)
LIST_FILE="/tmp/phpcs-list-${RANDOM}"
IFS=''; echo $STAGED > $LIST_FILE

PASSED=1
if [ "$STAGED" != "" ]
then
    echo "Checking compliance with Drupal coding standards ..."
    ./vendor/bin/phpcs --file-list=$LIST_FILE
    if [ $? != 0 ]
    then
        PASSED=0
    fi

    if [ $PASSED != 1 ]
    then
        echo "Fix the problems reported and try again ..."
        exit 1
    fi
fi

rm -f $LIST_FILE;

exit 0
